### ISSUE TITLE
Suggestion to rename repo/firmware to OXRS-AC-StateIO-KINCONY-FW

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-kinconyStateIO-ESP32-FW#1]
I.e. it is StateIO firmware for the Kincony platform. Could do `OXRS-AC-StateIO-KinconyESP32-FW` but I think `-KINCONY` is probably descriptive enough.

**Comment by austinscreations** [comment]
good suggestion - has been changed

**Comment by sumnerboy12** [comment]
Sorry to be pedantic - should be "StateIO" - i.e. capital "S".

**Comment by sumnerboy12** [comment]
And update the readme... :)

**Comment by austinscreations** [comment]
should be fixed now ;)
